apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namespace: expense-dev
images:
  - name: uptimecrew/expense-api
    newName: uptimecrew/expense-api
    newTag: 0.1.0
replicas:
  - name: expense-api
    count: 1
patches:
  - target: { kind: ConfigMap, name: expense-api-config }
    patch: |-
      - op: replace
        path: /data/LOGGING_LEVEL_ROOT
        value: DEBUG
